### ISSUE TITLE
Possible incompatible with AzureDoom's Doom Mod

### ISSUE THREAD

**Issue by TheButterbrotMan** [How-Bout-No/Outvoted#11]
**Describe the bug**
I created my own modpack, with a bunch of mods. It looks like Outvoted is not compatible, with AzureDoom's Doom Mod. If i move Outvoted in the modlist, game crash instantly after loading with error -1.

**Screenshots/Logs**
latest.log: https://pastebin.com/T8aY0uJj

debuglog: https://pastebin.com/x0X79Uvh

**Version (please complete the following information):**
 - Minecraft Version [1.16.4]
 - Mod Version [b0.3.1-2]

**Comment by How-Bout-No** [comment]
I speculate that this is in part due to how the current public versions of Outvoted use Geckolib 2, while AzureDoom's mod uses Geckolib 3 beta. Although the logs seem to indicate an issue on the Doom Mod's mixin configuration.
I think Geckolib allows you to run versions 2.x.x and 3.0.0-betas alongside each other (just not in Twitch/similar launchers), do you get the same crash if you have both Geckolib versions?

**Comment by TheButterbrotMan** [comment]
Hey, sorry for late reply. Was busy.

So i installed actually 2.x.x and 3.0.0 beta. It look like it works now (No Crashs). 

Thank you. =)

**Comment by How-Bout-No** [comment]
No problem! Just keep note that the next update will use Geckolib 3.0.0 so you won't need to use 2 different versions.
