### ISSUE TITLE
Add EntityClassification.Monster to hostile mobs

### ISSUE THREAD

**Issue by ricksouth** [How-Bout-No/Outvoted#35]
Hi! Someone opened an issue for my mod which disables hostile mob spawns around the campfire. It checks for the classification "EntityClassification.Monster" and if it exists, cancels the spawn. It seems "Hunger's" can still spawn.

Adding the classification should fix the problem. I haven't tested it myself, hope I don't make wrong assumptions. Thanks!

https://github.com/ricksouth/serilum-mc-mods/issues/504

**Comment by How-Bout-No** [comment]
The Hunger isn't classified as a Monster because it's not necessarily a hostile mob. It's abilities are useful to a point where it is allowed to spawn in Peaceful (which also disables its attacking), hence it not being labeled as a Monster. It does use Monster spawning rules, but I assume that has no affect in this scenario.
Not really sure how to go about this, and I've already stated why it's not being classified as a monster.

**Comment by ricksouth** [comment]
I see. Do you think it should be blocked by an entity that disables hostile mob spawning? Or leave it as is?

**Comment by How-Bout-No** [comment]
Sorry for very late reply. I've gone about this by just setting the Hunger as a Monster but just overriding it to not despawn in peaceful. This should fix this issue.
