### ISSUE TITLE
I would like you to add more features to the kraken

### ISSUE THREAD

**Issue by Abishark** [How-Bout-No/Outvoted#36]
I really don't like that the only thing the kraken does is drag you to the bottom of the sea waiting for you to drown, it gives you enough time to do it with a sword or if one has a potion of aquatic breathing, the kraken becomes totally harmless, I think it is the least flashy and useful mob.

I wish the kraken had more attacks, like biting you with its jaws or locking you in with these so you can drown faster. I would also like the kraken to eat the villagers, to make it more difficult when you carry them in boats. I also think that you could create a new tool with its tongue, like a whip that draws enemies towards you, like a fishing rod but that catches enemies.

Well, that was my suggestion, I hope you can take it into account :D

**Comment by How-Bout-No** [comment]
Well there's a couple things I'd like to note:
When grabbed by the Kraken, the player's oxygen decreases at a faster rate than if they were just diving under water. Also, having water breathing has no effect if you are grabbed by the Kraken. It will still deal damage and consume oxygen as if you didn't have the effect. The main status effect that has any affect on the Kraken is Dolphin's Grace, which causes you to be functionally "invisible" to Krakens.

As for everything else, both its attacks and movement mechanics had to change significantly in development, mainly due to my inexperience, others due to limitations in code. If I get around to reimplementing the original design ideas from early development, then the Kraken will be a bit more diverse in what it can do (there are some unused animations if I didn't remove them). This includes tools and such that would've utilized special drops.
For the Villager thing, I can (maybe) make it so it can attack Villagers with its current attack mechanics, but I'm unsure how well it will play out in game or if it would be way too annoying to deal with.

**Comment by How-Bout-No** [comment]
This is in except for the villager and new tool stuff. Since I'm not sure if I'm going to implement the latter at this time, I'll close this.
