### ISSUE TITLE
Crash with Netherite Plus Mod.

### ISSUE THREAD

**Issue by jahirtrap** [How-Bout-No/Outvoted#44]
**Describe the bug**
The game crashes when using mods:
- Outvoted
- [Netherite Plus mod](https://www.curseforge.com/minecraft/mc-mods/netherite-plus-mod/files/3273335)

**To Reproduce**
 - Use only Netherite plus and Outvoted mods with their respective dependencies

**Version**
 - Minecraft Version [1.16.5]
 - Mod Version [2.0.0-alpha.2-forge]

**Log**
 - [latest.log](https://github.com/How-Bout-No/Outvoted/files/6423913/latest.log)

psdt: Mod Version [2.0.0-alpha.1-forge] works correctly

**Comment by How-Bout-No** [comment]
Yea, I don't know whether the issue lies in my implementation or Oro's implementation. It doesn't crash with alpha.1 because shields didn't work properly in alpha.1, and were fixed in alpha.2, but clearly this is causing issues.
I'm gonna go on the safe side and say my implementation is the problem.

**Comment by celsiusqc** [comment]
https://gist.github.com/celsiusqc/d581b901790192e17b3144e5b595c3c6

Same issue here

**Comment by How-Bout-No** [comment]
Will be fixed in alpha.3
