### ISSUE TITLE
Over-enchanting with More Power

### ISSUE THREAD

**Issue by LeonaFlair** [How-Bout-No/Outvoted#55]
**Is your feature request related to a problem? Please describe.**
I'm always searching for a new way to do things, and I've always had a real soft spot for making cool, legendarily enchanted items.

**Describe the solution you'd like**
Throw a nether star into the maw of the Hunger along with two overenchanted items to allow for the creation of even higher overenchantments.

**Describe alternatives you've considered**
You could also use a netherite ingot or a new item made with a netherite ingot and a nether star.

**Additional context**
Also, for this to work, the Hunger would need to process items/enchantments 100% efficiently. Imagine making a Knockback V book only to get it voided for, from a player's perspective, no good reason.

**Comment by How-Bout-No** [comment]
This kind of steps too far outside the vanilla+ aspect of the mod. Overenchanting has its limitations because getting crazy high overpowered items would be too much for a vanilla-esque playstyle. Sure, it may be cool to get Sharpness X, but it doesn't really fit.

**Comment by How-Bout-No** [comment]
Due to my philosophy on giving users freedom of choice, this is sort of put in place now with the `capEnchants` option in the config, which disables the overenchant cap of 1 above max level. Do note that this method would be *very* tedious to get extremely high enchants as it still follows normal rules (i.e. you can't have multiple of the same enchantment stored, so you will have to constantly use items to get the overenchant out and repeat the process) as otherwise I would've had to rewrite significant portions of the Glutton enchant code just for this feature which was too much of a task.

I may revisit this in the future, but for now this is how it will be.
