### ISSUE TITLE
[BUG] Kraken/Monster of the Ocean Depths (Visual Glitch) [Fabric 1.17.1]

### ISSUE THREAD

**Issue by Ahdie1** [How-Bout-No/Outvoted#63]
When out of the water or in the water looking away from the kraken, when the kraken is just on the edge of the end of the screen, it will disappear then reappear when at least half of its body is in view again. Hard to explain but only happens with the MOTOD, might want to go in game to see this in action.

**Comment by Ahdie1** [comment]
![2021-08-05_18 15 17](https://user-images.githubusercontent.com/88512999/128428326-f3e36f5e-6331-4faa-b8a3-591a0805c1cc.png)

**Comment by Ahdie1** [comment]
^^^^ When looking about here, in this position and slowly moving your view around, you will notice the Barnacle/MOTOD pop in and out visually.

**Comment by How-Bout-No** [comment]
I suspect this might happen because of the Barnacle's hitbox compared to its size (it's hitbox only surrounds its head and not its tentacles) so when the hitbox is off screen the game believes that the mob is no longer in the player's view. If that is the case, then there isn't much I can do since I can't expand its hitbox as the Barnacle's movements are too complex to get a hitbox that makes sense.
