### ISSUE TITLE
Compatibility with mods that change worldgen and biomes

### ISSUE THREAD

**Issue by Protozoare** [How-Bout-No/Outvoted#74]
I am playing with outvoted and all the biomes you'll go (improves existing biomes) also oh the biomes you'll go (adds new biomes.) The mobs added by the outvoted mod do not spawn naturally in the world, not even on regular biomes (because atbg changes regular biomes). I made a deep ocean only world, yet i failed to find a kraken with 100 spawn rate in config.

**Comment by How-Bout-No** [comment]
Biome compatibility will be up to the user. Since it would take forever for me to add compatibility with each possible worldgen mod. You can go into the config for each mobs spawn biomes and either set biome tags (such as `#desert` to spawn in everything tagged as a desert) or if you want to spawn in specific OTBYG biomes I believe you can specify it like `byg:whateverbiome` but not too sure on that.

**Comment by How-Bout-No** [comment]
This is why only Gluttons are spawning as they (except or Ostriches) are the only mobs using biome tags by default. You can peek into the config to see.
