### ISSUE TITLE
Oxidized Copper Golems reset pose after rejoin on single player[BUG]

### ISSUE THREAD

**Issue by frikinjay** [How-Bout-No/Outvoted#97]
/Before submitting, please ensure you've done the following, as these are fixes for some common bugs:
[ ] Reset/delete config files
[ ] Run without mods like Optifine (if needed)
[ ] <ins>Double check that you have the latest version!!</ins>

**Describe the bug**
Oxidized Copper Golems reset pose after rejoin on single player.

**To Reproduce**
1. Create a single player world.
2. Spawn a copper golem.
3. Wait for it to oxidize.
4. Leave the world and rejoin.

**Screenshots/Logs**
Before
![image](https://user-images.githubusercontent.com/88995340/138898516-0b0b9ae6-5ed8-4455-a3d4-29c15b72d11c.png)

After
![image](https://user-images.githubusercontent.com/88995340/138898726-9bf79641-8664-454f-8197-4fbf4d8aaa20.png)

**Version (please complete the following information):**
 - 1.17.1
 - Fabric
 - 1.5.0-beta.1

**Additional context**
--

**Comment by How-Bout-No** [comment]
Oh what. Wondering what caused this to break. Can you confirm if it only happens in singleplayer?

**Comment by frikinjay** [comment]
I havent tried it on a server, but i can confirm it happens on single player.

**Comment by SplendidAlakey** [comment]
It happens on servers too.

Before restart: 
![2021-10-26_22 58 48](https://user-images.githubusercontent.com/86702831/138960609-d27b0a32-0acf-4dba-bd37-aaaed970fbf2.png)

After: 
![2021-10-26_23 02 54](https://user-images.githubusercontent.com/86702831/138960631-2e02371b-c5b4-4712-8a3a-2d07a670343f.png)

There's also a [Mob Catcher](https://www.curseforge.com/minecraft/mc-mods/mob-catcher-fabric) mod that makes it very easy to replicate without restarting. Just catch fully oxidized golems and place them down, they will change stances every single time.

**Comment by How-Bout-No** [comment]
Somewhat fixed in beta 2, however it needs a bit more work due to client/server desync so I'm leaving this open until then.

Here's the current issue: if the Golem oxidizes and then rotates after it's frozen, then its actual position/rotation is where it was before it rotated (as this rotation only happens on the client side). The client gets updated with the server values on relog, but I'm working on a way to get them properly synced. Still, this is a big improvement over the poses not saving at all, but it obviously still needs a bit of tweaking. If the Golem does not rotate after it oxidizes then the client and server should have the same position.

**Comment by How-Bout-No** [comment]
Closing this now since any desync in the current versions seems to be sufficiently corrected.
